name: Build
run-name: ${{ github.actor }} is building app for ${{ github.ref }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          options: --verbose
          meson-version: 0.53.2
          ninja-version: 1.9.0.post1
          gcovr-version: 4.2
