name: Build
run-name: ${{ github.actor }} is building app for ${{ github.ref }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Copy Repo
      - uses: actions/checkout@v3
      # Install meson
      - run: sudo apt install curl -y
      - run: curl -s https://raw.githubusercontent.com/mesonbuild/meson/master/ci/ciimage/ubuntu-rolling/install.sh | sudo bash
      # Setup build
      - run: meson setup build
      # Compile build
      - run: meson compile main -C build
      # Confirm main exit code is 0
