name: Build
run-name: ${{ github.actor }} is building app for ${{ github.ref }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Copy Repo
      - uses: actions/checkout@v3
      # Install perequesites
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install meson
      # Setup build
      - run: meson setup build
      # Compile build
      - run: meson compile -C build
